// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCosLfHKw1_jTjaE_OeqrPORmO2y7ipZdI',
    appId: '1:360891009242:web:aa424ca4d6a4378293bde3',
    messagingSenderId: '360891009242',
    projectId: 'adhive-5073d',
    authDomain: 'adhive-5073d.firebaseapp.com',
    storageBucket: 'adhive-5073d.firebasestorage.app',
    measurementId: 'G-TVDPB72E19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRbVPEcOmKWW38f8h0fDGnsLIxYMwcIrA',
    appId: '1:360891009242:android:56b64b73dd0d744093bde3',
    messagingSenderId: '360891009242',
    projectId: 'adhive-5073d',
    storageBucket: 'adhive-5073d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgCyOie6r1yqCJpN4OgrhqMZ3-AxTiMBI',
    appId: '1:360891009242:ios:76bbd88ba47dbd2793bde3',
    messagingSenderId: '360891009242',
    projectId: 'adhive-5073d',
    storageBucket: 'adhive-5073d.firebasestorage.app',
    iosBundleId: 'com.example.adHive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgCyOie6r1yqCJpN4OgrhqMZ3-AxTiMBI',
    appId: '1:360891009242:ios:76bbd88ba47dbd2793bde3',
    messagingSenderId: '360891009242',
    projectId: 'adhive-5073d',
    storageBucket: 'adhive-5073d.firebasestorage.app',
    iosBundleId: 'com.example.adHive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCosLfHKw1_jTjaE_OeqrPORmO2y7ipZdI',
    appId: '1:360891009242:web:b4f225a54f0d0fe093bde3',
    messagingSenderId: '360891009242',
    projectId: 'adhive-5073d',
    authDomain: 'adhive-5073d.firebaseapp.com',
    storageBucket: 'adhive-5073d.firebasestorage.app',
    measurementId: 'G-38HQ49BV9F',
  );
}
